[agent]
  hostname = "telegraf-01"

###############################################################################
#                            DATA COLLECTION                                  #
###############################################################################

[[inputs.ping]]
  interval = "10s"
  count = 3
  ping_interval = 1.0
  timeout = 5.0
  urls = ["srl1"]

  [inputs.ping.tags]
    collection_type = "ping"
    watcher_type = "healthcheck"
    service = "srl1"

##############################################################################
#                            DATA NORMALIZATION                              #
##############################################################################


###############################################################################
#                            DATA ENRICHMENT                                  #
###############################################################################


##############################################################################
#                            DATA OUTPUT                                     #
##############################################################################
[[outputs.file]]
  files = ["stdout"]
